# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

type: 'scene'

PerspectiveCamera:
  type: 'perspective'
  fov: 45
  film:
    type: 'hdrfilm'
    width: 1920
    height: 1080
    rfilter:
      type: 'box'
  
Integrator:
  type: 'path'
  max_depth: 7

main_scene:
  type: 'ply'
  filename: ''
  bsdf:
    type: 'twosided'
    fipt_bsdf:
      type: 'fipt'
      emitter_path: ''
      brdf_path: ''

emitter_room2:
  type: 'ply'
  filename: 'checkpoints/scannetpp_room2/bake/emitter.ply'
  to_world:
    - type: 'translate'
      value: [0.0, 0.0, 0.0]
    - type: 'scale'
      value: [1.0, 1.0, 1.0]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [8.679976, 8.248041, 2.860989]

andersen: 
  type: 'obj'
  filename: 'outputs/00_assets/hans-christian-andersen/source/HansChristianAndersen/HansChristianAndersen-80k.obj'
  to_world:
    - type: 'translate'
      value: [-0.192385 , -0.926694, 0.643368]
    - type: 'scale'
      value: [0.015, 0.015, 0.015]
    - type: 'rotate'
      axis: [1, 0, 0]
      angle: 180
  bsdf:
    type: 'roughconductor'
    distribution: 'ggx'
    alpha_u: 0.05
    alpha_v: 0.3
    eta: 
      type: 'rgb'
      value: [0.47, 0.35, 0.29]
    k: 
      type: 'rgb'
      value: [0.332, 0.239, 0.235]
    
bunny: 
  type: 'obj'
  filename: 'outputs/00_assets/stanford-bunny.obj'
  to_world:
    - type: 'translate'
      value: [-0.515105, -0.626611, 0.3113]
    - type: 'scale'
      value: [2, 2, 2]
    - type: 'rotate'
      axis: [1, 0, 0]
      angle: -90
    - type: 'rotate'
      axis: [0, 1, 0]
      angle: 90
  bsdf:
    type: 'conductor'
    material: 'Cu'